import { Link } from "@tanstack/react-router";
import { ArrowUpRight } from "lucide-react";
import { Brand } from "./brand";
import { Container } from "./primitives";
import { company } from "@/data/company";
import { productCategories } from "@/data/products";
import { solutions } from "@/data/solutions";

const links = [{ label: "Home", to: "/" }, { label: "About", to: "/about" }, { label: "Products", to: "/products" }, { label: "Solutions", to: "/solutions" }, { label: "Bulk Orders", to: "/bulk-orders" }, { label: "Contact", to: "/contact" }];
function FooterLinks({ title, items }: { title: string; items: { label: string; to: string }[] }) { return <div><h2 className="mb-5 text-xs font-bold uppercase text-background/55">{title}</h2><ul className="space-y-3">{items.map((item) => <li key={item.to}><Link to={item.to} className="text-sm text-background/80 transition-colors hover:text-background">{item.label}</Link></li>)}</ul></div>; }
export function Footer() { return <footer className="bg-ink text-background"><Container className="grid gap-12 py-16 sm:grid-cols-2 lg:grid-cols-[1.4fr_1fr_1fr_1fr]"><div><Brand className="w-44 bg-background p-2" /><p className="mt-6 max-w-sm text-sm leading-7 text-background/65">{company.description}</p><p className="mt-5 text-sm font-bold text-background">{company.tagline}</p></div><FooterLinks title="Quick links" items={links} /><FooterLinks title="Products" items={productCategories.map((item) => ({ label: item.name, to: `/products/${item.slug}` }))} /><FooterLinks title="Solutions" items={solutions.map((item) => ({ label: item.name, to: `/solutions/${item.slug}` }))} /><div className="sm:col-span-2 lg:col-start-2 lg:col-span-3"><Link to="/quote" className="inline-flex items-center gap-2 text-lg font-bold text-background hover:text-secondary">Discuss your requirement <ArrowUpRight /></Link>{!company.contact.address && <p className="mt-3 text-xs text-background/45">Showroom and contact details will be published once confirmed.</p>}</div></Container><div className="border-t border-background/10"><Container className="flex flex-col gap-2 py-5 text-xs text-background/50 sm:flex-row sm:items-center sm:justify-between"><p>© KUBERR PLYWOOD. All rights reserved.</p><p>Complete Interior & Furniture Material Solutions</p></Container></div></footer>; }
