/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BulkOrdersRouteImport } from './routes/bulk-orders'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProductsSlugRouteImport } from './routes/products/$slug'
import { Route as SolutionsIndexRouteImport } from './routes/solutions/index'
import { Route as SolutionsSlugRouteImport } from './routes/solutions/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkOrdersRoute = BulkOrdersRouteImport.update({
  id: '/bulk-orders',
  path: '/bulk-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsIndexRoute = SolutionsIndexRouteImport.update({
  id: '/solutions/',
  path: '/solutions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsSlugRoute = SolutionsSlugRouteImport.update({
  id: '/solutions/$slug',
  path: '/solutions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bulk-orders': typeof BulkOrdersRoute
  '/contact': typeof ContactRoute
  '/quote': typeof QuoteRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/products/': typeof ProductsIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bulk-orders': typeof BulkOrdersRoute
  '/contact': typeof ContactRoute
  '/quote': typeof QuoteRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/products': typeof ProductsIndexRoute
  '/solutions': typeof SolutionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bulk-orders': typeof BulkOrdersRoute
  '/contact': typeof ContactRoute
  '/quote': typeof QuoteRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/products/': typeof ProductsIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bulk-orders'
    | '/contact'
    | '/quote'
    | '/products/$slug'
    | '/solutions/$slug'
    | '/products/'
    | '/solutions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bulk-orders'
    | '/contact'
    | '/quote'
    | '/products/$slug'
    | '/solutions/$slug'
    | '/products'
    | '/solutions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bulk-orders'
    | '/contact'
    | '/quote'
    | '/products/$slug'
    | '/solutions/$slug'
    | '/products/'
    | '/solutions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BulkOrdersRoute: typeof BulkOrdersRoute
  ContactRoute: typeof ContactRoute
  QuoteRoute: typeof QuoteRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  SolutionsSlugRoute: typeof SolutionsSlugRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  SolutionsIndexRoute: typeof SolutionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk-orders': {
      id: '/bulk-orders'
      path: '/bulk-orders'
      fullPath: '/bulk-orders'
      preLoaderRoute: typeof BulkOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/': {
      id: '/solutions/'
      path: '/solutions'
      fullPath: '/solutions/'
      preLoaderRoute: typeof SolutionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/$slug': {
      id: '/solutions/$slug'
      path: '/solutions/$slug'
      fullPath: '/solutions/$slug'
      preLoaderRoute: typeof SolutionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BulkOrdersRoute: BulkOrdersRoute,
  ContactRoute: ContactRoute,
  QuoteRoute: QuoteRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  SolutionsSlugRoute: SolutionsSlugRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  SolutionsIndexRoute: SolutionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
